name: lazylist
description: "A Flutter package that provides a lazy-loading list view with customizable features and a controller for external control over list behavior.
"
version: 0.0.1
homepage: https://github.com/sina-moradbakhti/lazylist

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
